name: admin
public: true
named: {}
views:
  uesio/cms.admin_nav: true
  uesio/cms.article_detail: true
  uesio/cms.article_list: true
  uesio/cms.article_new: true
  uesio/cms.article_public: true
  uesio/cms.author_detail: true
  uesio/cms.author_list: true
  uesio/cms.author_new: true
  uesio/cms.category_detail: true
  uesio/cms.category_list: true
  uesio/cms.category_new: true
  uesio/cms.series_detail: true
  uesio/cms.series_list: true
  uesio/cms.series_nav: true
  uesio/cms.series_new: true
  uesio/cms.track_detail: true
  uesio/cms.track_list: true
  uesio/cms.track_nav: true
  uesio/cms.track_new: true
collections:
  uesio/cms.article:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/cms.author:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/cms.author_link:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/cms.category:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/cms.series:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/cms.series_track:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/cms.track:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/cms.track_article:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/core.user:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
  uesio/core.userfile:
    read: true
    create: true
    edit: true
    delete: true
    modifyall: false
    viewall: false
    fields: {}
routes:
  uesio/cms.article_detail: true
  uesio/cms.article_list: true
  uesio/cms.article_new: true
  uesio/cms.article_public: true
  uesio/cms.author_detail: true
  uesio/cms.author_list: true
  uesio/cms.author_new: true
  uesio/cms.category_detail: true
  uesio/cms.category_list: true
  uesio/cms.category_new: true
  uesio/cms.series_detail: true
  uesio/cms.series_list: true
  uesio/cms.series_new: true
  uesio/cms.track_detail: true
  uesio/cms.track_list: true
  uesio/cms.track_new: true
files: {}
bots: {}
integrationActions: {}
allowallbots: false
allowallcollections: false
allowallviews: false
allowallroutes: false
allowallfiles: true
allowallintegrationactions: false
modifyallrecords: false
viewallrecords: false
