name: Main Branch Build
on:
  push:
    branches:
      - main

jobs:
  bundle_dev:
    name: Create patch bundle in DEV
    uses: ./.github/workflows/bundle.yaml
    with:
      environment: dev
      type: patch
    secrets: inherit
  bundle_prod:
    name: Create patch bundle in PROD
    needs: bundle_dev
    uses: ./.github/workflows/bundle.yaml
    with:
      environment: prod
      type: patch
    secrets: inherit
