name: Manual bundle creation

# We must always create the same bundles in dev and prod for consistency,
# otherwise builds of web/docs/etc. apps may succeed to dev but fail in prod,
# or vice versa

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Bundle type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bundle_dev:
    name: Create ${{ inputs.type }} bundle in DEV environment
    uses: ./.github/workflows/bundle.yaml
    with:
      environment: dev
      type: ${{ inputs.type }}
    secrets: inherit
  bundle_prod:
      name: Create ${{ inputs.type }} bundle in PROD environment
      uses: ./.github/workflows/bundle.yaml
      needs: bundle_dev
      with:
        environment: prod
        type: ${{ inputs.type }}
      secrets: inherit
